const groups = [
 ['north-indian','North Indian','North Indian Classics',['Curries & Dal','Breads','Rice & Biryani','Tandoor & Starters']],
 ['punjabi','Punjabi','Punjabi Kitchen',['Dal & Chole','Paneer Specials','Punjabi Breads','Combos']],
 ['south-indian','South Indian','South Indian Kitchen',['Dosa','Idli & Vada','Uttapam','South Indian Meals']],
 ['italian','Italian','Italian Favourites',['Pizza','Pasta','Risotto']],
 ['continental','Continental','Continental Plates',['Mains','Soups & Salads','Sandwiches']],
 ['chinese','Chinese','Indo-Chinese',['Noodles','Fried Rice','Manchurian']],
 ['starters','Starters','Small Plates & Starters',['Veg Starters','Tandoor Starters']],
 ['snacks','Snacks','Quick Bites',['Sandwiches','Fries & Sides','Chaat']],
 ['beverages','Beverages','Drinks & Refreshments',['Tea','Coffee','Cold Beverages','Mocktails','Juices']],
 ['desserts','Desserts','Desserts & Sweet Treats',['Indian Sweets','Cakes & Pastries','Ice Cream']],
 ['thalis','Thalis & Combos','Complete Meals',['Indian Thalis','South Indian Combos']],
];
const items = [
['Paneer Butter Masala','punjabi','Paneer Specials',320,'Creamy tomato gravy with soft paneer.'],['Shahi Paneer','punjabi','Paneer Specials',340,'Paneer in a rich cashew and cream gravy.'],['Dal Makhani','punjabi','Dal & Chole',290,'Slow-cooked black lentils finished with butter.'],['Dal Tadka','north-indian','Curries & Dal',220,'Yellow lentils tempered with cumin, garlic and ghee.'],['Chole Masala','punjabi','Dal & Chole',230,'Punjabi chickpea curry with warming spices.'],['Kadhai Paneer','north-indian','Curries & Dal',310,'Paneer tossed with peppers and crushed spices.'],['Mix Veg Curry','north-indian','Curries & Dal',240,'Seasonal vegetables in a homestyle masala.'],['Butter Naan','north-indian','Breads',65,'Soft tandoor-baked naan brushed with butter.'],['Garlic Naan','north-indian','Breads',85,'Naan topped with garlic and coriander.'],['Tandoori Roti','north-indian','Breads',35,'Whole-wheat roti from the clay oven.'],['Jeera Rice','north-indian','Rice & Biryani',180,'Basmati rice tempered with cumin.'],['Veg Dum Biryani','north-indian','Rice & Biryani',280,'Fragrant basmati and vegetables, slow cooked.'],['Paneer Tikka','starters','Veg Starters',280,'Chargrilled marinated paneer with peppers.'],['Hara Bhara Kebab','starters','Veg Starters',220,'Spinach and green-pea kebabs.'],['Veg Seekh Kebab','starters','Tandoor Starters',250,'Smoky minced vegetable kebabs.'],['Masala Dosa','south-indian','Dosa',150,'Crisp dosa with spiced potato masala.'],['Plain Dosa','south-indian','Dosa',110,'Golden, crisp fermented rice-lentil crepe.'],['Mysore Masala Dosa','south-indian','Dosa',180,'Dosa with spicy Mysore chutney and potato.'],['Idli Sambhar','south-indian','Idli & Vada',120,'Steamed idlis served with sambhar and chutney.'],['Medu Vada','south-indian','Idli & Vada',110,'Crisp lentil doughnuts with coconut chutney.'],['Onion Uttapam','south-indian','Uttapam',150,'Soft rice pancake topped with onion.'],['South Indian Meals','south-indian','South Indian Meals',260,'Traditional meal with rice, sambhar and sides.'],['Margherita Pizza','italian','Pizza',299,'Tomato, mozzarella and fresh basil.'],['Farmhouse Pizza','italian','Pizza',399,'Loaded with garden vegetables and cheese.'],['Penne Alfredo','italian','Pasta',330,'Penne tossed in a creamy parmesan-style sauce.'],['Arrabbiata Pasta','italian','Pasta',310,'Pasta in a spicy tomato and garlic sauce.'],['Veg Lasagna','italian','Pasta',390,'Layered pasta with vegetables and cheese.'],['Grilled Veg Sandwich','continental','Sandwiches',190,'Toasted sandwich with grilled vegetables.'],['Cream of Tomato Soup','continental','Soups & Salads',150,'Silky tomato soup with herbs.'],['Veg Sizzler','continental','Mains',390,'Grilled vegetables, rice and house sauce.'],['Hakka Noodles','chinese','Noodles',220,'Wok-tossed noodles with vegetables.'],['Chilli Paneer','chinese','Manchurian',280,'Paneer tossed in a tangy chilli sauce.'],['Veg Fried Rice','chinese','Fried Rice',210,'Wok-fried rice with seasonal vegetables.'],['Veg Manchurian','chinese','Manchurian',230,'Crispy vegetable dumplings in savoury sauce.'],['Samosa','snacks','Chaat',35,'Crisp pastry filled with spiced potato.'],['Pani Puri','snacks','Chaat',80,'Crisp puris with tangy flavoured water.'],['French Fries','snacks','Fries & Sides',120,'Golden fries with a seasoning of your choice.'],['Veg Cheese Sandwich','snacks','Sandwiches',170,'Grilled sandwich with vegetables and cheese.'],['Masala Chai','beverages','Tea',50,'Indian tea brewed with ginger and spices.'],['Adrak Chai','beverages','Tea',55,'Fresh ginger tea with milk.'],['Green Tea','beverages','Tea',70,'Light aromatic green tea.'],['Cappuccino','beverages','Coffee',140,'Espresso with steamed milk foam.'],['Cafe Latte','beverages','Coffee',150,'Smooth espresso with silky steamed milk.'],['Cold Coffee','beverages','Cold Beverages',170,'Chilled coffee blended with milk.'],['Fresh Lime Soda','beverages','Cold Beverages',110,'Fresh lime with soda, sweet or salted.'],['Mango Shake','beverages','Cold Beverages',180,'Thick mango milkshake.'],['Virgin Mojito','beverages','Mocktails',190,'Mint, lime and sparkling soda.'],['Watermelon Juice','beverages','Juices',130,'Fresh seasonal watermelon juice.'],['Gulab Jamun','desserts','Indian Sweets',90,'Warm milk-solid dumplings in sugar syrup.'],['Gajar Halwa','desserts','Indian Sweets',140,'Carrot pudding finished with nuts.'],['Rasmalai','desserts','Indian Sweets',120,'Soft chenna dumplings in saffron milk.'],['Chocolate Brownie','desserts','Cakes & Pastries',160,'Warm chocolate brownie.'],['Chocolate pastry','desserts','Cakes & Pastries',140,'Rich layered chocolate pastry.'],['Vanilla Ice Cream','desserts','Ice Cream',100,'Classic creamy vanilla scoop.'],['Papad','north-indian','Curries & Dal',35,'Crisp roasted papad.'],['Punjabi Thali','thalis','Indian Thalis',350,'A complete meal with curry, dal, breads and rice.'],['South Indian Combo','thalis','South Indian Combos',240,'Dosa, idli, sambhar and chutneys.']
];

//chnages
const categoryHindi = {
  "north-indian": "उत्तर भारतीय",
  punjabi: "पंजाबी",
  "south-indian": "दक्षिण भारतीय",
  italian: "इटैलियन",
  continental: "कॉन्टिनेंटल",
  chinese: "चाइनीज़",
  starters: "स्टार्टर",
  snacks: "नाश्ता",
  beverages: "पेय पदार्थ",
  desserts: "मिठाइयाँ",
  thalis: "थाली और कॉम्बो",
};

const subHindi = {
  "Curries & Dal": "करी और दाल",
  Breads: "रोटियाँ",
  "Rice & Biryani": "चावल और बिरयानी",
  "Tandoor & Starters": "तंदूरी और स्टार्टर",
  "Dal & Chole": "दाल और छोले",
  "Paneer Specials": "पनीर स्पेशल",
  "Punjabi Breads": "पंजाबी रोटियाँ",
  Combos: "कॉम्बो",
  Dosa: "डोसा",
  "Idli & Vada": "इडली और वड़ा",
  Uttapam: "उत्तपम",
  "South Indian Meals": "दक्षिण भारतीय भोजन",
  Pizza: "पिज़्ज़ा",
  Pasta: "पास्ता",
  Risotto: "रिसोट्टो",
  Mains: "मुख्य व्यंजन",
  "Soups & Salads": "सूप और सलाद",
  Sandwiches: "सैंडविच",
  Noodles: "नूडल्स",
  "Fried Rice": "फ्राइड राइस",
  Manchurian: "मंचूरियन",
  "Veg Starters": "वेज स्टार्टर",
  "Tandoor Starters": "तंदूरी स्टार्टर",
  "Fries & Sides": "फ्राइज़ और साइड्स",
  Chaat: "चाट",
  Tea: "चाय",
  Coffee: "कॉफी",
  "Cold Beverages": "ठंडे पेय",
  Mocktails: "मॉकटेल",
  Juices: "जूस",
  "Indian Sweets": "भारतीय मिठाइयाँ",
  "Cakes & Pastries": "केक और पेस्ट्री",
  "Ice Cream": "आइसक्रीम",
  "Indian Thalis": "भारतीय थाली",
  "South Indian Combos": "दक्षिण भारतीय कॉम्बो",
};
const categories = groups.map(([id, name, title, subs]) => ({
  id,
  label: {
    en: name,
    hi: categoryHindi[id] || name,
  },
  title: {
    en: title,
    hi: title,
  },
  subCategories: subs.map((s) => ({
    id: `${id}-${s.toLowerCase().replace(/[^a-z0-9]+/g, "-")}`,
    label: {
      en: s,
      hi: subHindi[s] || s,
    },
  })),
}));
const dishHindi = {
  "Paneer Butter Masala": "पनीर बटर मसाला",
  "Shahi Paneer": "शाही पनीर",
  "Dal Makhani": "दाल मखनी",
  "Dal Tadka": "दाल तड़का",
  "Chole Masala": "छोले मसाला",
  "Kadhai Paneer": "कड़ाही पनीर",
  "Mix Veg Curry": "मिक्स वेज करी",
  "Butter Naan": "बटर नान",
  "Garlic Naan": "गार्लिक नान",
  "Tandoori Roti": "तंदूरी रोटी",
  "Jeera Rice": "जीरा राइस",
  "Veg Dum Biryani": "वेज दम बिरयानी",
  "Paneer Tikka": "पनीर टिक्का",
  "Hara Bhara Kebab": "हरा भरा कबाब",
  "Veg Seekh Kebab": "वेज सीख कबाब",
  "Masala Dosa": "मसाला डोसा",
  "Plain Dosa": "सादा डोसा",
  "Mysore Masala Dosa": "मैसूर मसाला डोसा",
  "Idli Sambhar": "इडली सांभर",
  "Medu Vada": "मेदु वड़ा",
  "Onion Uttapam": "प्याज़ उत्तपम",
  "South Indian Meals": "दक्षिण भारतीय भोजन",
  "Margherita Pizza": "मार्गरीटा पिज़्ज़ा",
  "Farmhouse Pizza": "फार्महाउस पिज़्ज़ा",
  "Penne Alfredo": "पेने अल्फ्रेडो",
  "Arrabbiata Pasta": "अर्राबियाटा पास्ता",
  "Veg Lasagna": "वेज लज़ान्या",
  "Grilled Veg Sandwich": "ग्रिल्ड वेज सैंडविच",
  "Cream of Tomato Soup": "टमाटर का क्रीमी सूप",
  "Veg Sizzler": "वेज सिज़लर",
  "Hakka Noodles": "हक्का नूडल्स",
  "Chilli Paneer": "चिली पनीर",
  "Veg Fried Rice": "वेज फ्राइड राइस",
  "Veg Manchurian": "वेज मंचूरियन",
  "Samosa": "समोसा",
  "Pani Puri": "पानी पुरी",
  "French Fries": "फ्रेंच फ्राइज़",
  "Veg Cheese Sandwich": "वेज चीज़ सैंडविच",
  "Masala Chai": "मसाला चाय",
  "Adrak Chai": "अदरक वाली चाय",
  "Green Tea": "ग्रीन टी",
  "Cappuccino": "कैपुचीनो",
  "Cafe Latte": "कैफ़े लाटे",
  "Cold Coffee": "कोल्ड कॉफी",
  "Fresh Lime Soda": "नींबू सोडा",
  "Mango Shake": "मैंगो शेक",
  "Virgin Mojito": "वर्जिन मोजिटो",
  "Watermelon Juice": "तरबूज़ का जूस",
  "Gulab Jamun": "गुलाब जामुन",
  "Gajar Halwa": "गाजर का हलवा",
  "Rasmalai": "रसमलाई",
  "Chocolate Brownie": "चॉकलेट ब्राउनी",
  "Chocolate pastry": "चॉकलेट पेस्ट्री",
  "Vanilla Ice Cream": "वनीला आइसक्रीम",
  "Papad": "पापड़",
  "Punjabi Thali": "पंजाबी थाली",
  "South Indian Combo": "दक्षिण भारतीय कॉम्बो",
};

const dishes = items.map(([name, category, sub, price, description], i) => ({
  id: `dish-${i + 1}`,
  name: {
    en: name,
    hi: dishHindi[name] || name,
  },
  category,
  subCategory: `${category}-${sub.toLowerCase().replace(/[^a-z0-9]+/g, "-")}`,
  price,
  rating: (4.5 + (i % 5) * 0.1).toFixed(1),
  prepTime: `${8 + (i % 5) * 4} mins`,
  image: `https://images.unsplash.com/photo-${[
    "1546833999-b9f581a1996d",
    "1567188040759-fb8a883dc6d8",
    "1563379091339-03b21ab4a4f8",
    "1513104890138-7c749659a591",
  ][i % 4]}?auto=format&fit=crop&w=800&q=80`,
  description: {
    en: description || `Freshly prepared ${name.toLowerCase()} made with quality ingredients.`,
    hi: `ताज़ी सामग्री से तैयार ${dishHindi[name] || name}।`,
  },
}));

export const DishModel={getLanguages:()=>[{code:'en',label:'English'},{code:'hi',label:'हिंदी'}],getOffers:()=>[{id:'off1',title:'THE CARTELL PRIVILEGE',discount:'20% OFF',code:'CARTELL20',description:'Enjoy 20% off your next order. A little indulgence, on us.',bannerImage:'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=900&q=80'},{id:'off2',title:'A LITTLE SIP OF JOY',discount:'BUY 1 GET 1',code:'SIPGOLD',description:'Buy one signature cooler and enjoy another on us.',bannerImage:'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=900&q=80'}],getCategories:()=>categories,getDishes:()=>dishes};
